### ISSUE TITLE
Window does not accept input when "addons" is closed

### ISSUE THREAD

**Issue by konnta0** [kubernetes-sigs/minikube-gui#50]
When I open a window from the "addons" button in the menu and close it, all the buttons in the menu are still disabled.
When the "addons" window is closed, the menu buttons should be enabled.
This is fixed by closing the window and reopening it from the system tray.

specs:
CPU: Apple M2 Pro
Mem: 32 GB
macOS: 13.2.1

https://user-images.githubusercontent.com/68390856/229303091-f7b8e148-aff6-495b-97b3-9741c177f233.mov

**Comment by spowelljr** [comment]
Hi @konnta0, this is fixed with https://github.com/kubernetes-sigs/minikube-gui/pull/39 and included in the v0.1.0 release
