### ISSUE TITLE
minikube-gui should have a setting page to override the minikube binary

### ISSUE THREAD

**Issue by medyagh** [kubernetes-sigs/minikube-gui#6]
currently minikube-gui uses whatever binary is in the path based on an order in this PR:
https://github.com/kubernetes-sigs/minikube-gui/pull/4

but it would be best if we have a settings page that would let you override/select the exact minikube binary to use (maybe show the version in parentheses 

(drop down menu)
- /usr/loca/bin/minikube (version 1.28.0)
- /opt/homebrew/bin/minikube  (version 1.27.1)
- ...
- 
or and maybe minikube gui should default to the latest version instead.

_Originally posted by @medyagh in https://github.com/kubernetes-sigs/minikube-gui/pull/4#pullrequestreview-1254175211_

**Comment by Sajiyah-Salat** [comment]
Please close this pr if its completed

**Comment by spowelljr** [comment]
Completed in
https://github.com/kubernetes-sigs/minikube-gui/pull/38
https://github.com/kubernetes-sigs/minikube-gui/pull/41
https://github.com/kubernetes-sigs/minikube-gui/pull/43
