### ISSUE TITLE
make minikube tray icon change color based on Status

### ISSUE THREAD

**Issue by medyagh** [kubernetes-sigs/minikube-gui#9]
minikube tray icon should be colorful when the cluster is running and it should be gray when it is not running

or maybe also if possible show the Icon with addtional Graphic (stop icon/pause/...)

**Comment by Sajiyah-Salat** [comment]
Can you please explain this in more detail

**Comment by medyagh** [comment]
Hi @Sajiyah-Salat thanks for showing interest, 
sure the current minikube tray icon is https://github.com/kubernetes-sigs/minikube-gui/tree/main/resources/images which is is a blue icon, I would the icon to show blue icon with a green dot whenever the clustre is running and when the cluster is stopped it should be Gray tray icon

**Comment by Sajiyah-Salat** [comment]
I think this issue needs some new img to add and some code. right? I am a beginner whose one pr have recently merged. Am I eligible to work on this?
